apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qbittorrent.fullname" . }}
spec:
  accessModes: [ {{ .Values.configStorage.accessMode }}]
  {{ if .Values.configStorage.storageClass }}
  storageClassName: {{ .Values.configStorage.storageClass }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.configStorage.size }}